#Data Preprocessing

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('/content/datasets_4458_8204_winequality-red.csv')

In [3]:
data

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [5]:
data['quality'].unique()

array([5, 6, 7, 4, 8, 3])

#Separate Features and Target

* Here lets considering 'quality' as target
*  and rest of the columns as features

In [6]:
x = data.iloc[:,:-1].values
y = data.iloc[:, -1].values

In [7]:
x

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [8]:
y

array([5, 5, 5, ..., 6, 5, 6])

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [11]:
y_train

array([3, 5, 6, ..., 6, 6, 5])

In [12]:
y_test

array([5, 5, 5, 6, 5, 7, 5, 5, 5, 6, 6, 5, 7, 5, 6, 7, 6, 5, 6, 6, 6, 6,
       6, 6, 5, 5, 5, 6, 5, 5, 5, 5, 6, 5, 5, 5, 3, 6, 6, 6, 6, 5, 6, 5,
       5, 6, 6, 6, 5, 5, 5, 6, 5, 5, 6, 6, 7, 6, 5, 5, 7, 7, 4, 5, 6, 5,
       6, 5, 6, 5, 5, 5, 6, 7, 5, 6, 6, 6, 7, 6, 7, 5, 4, 8, 7, 6, 6, 6,
       6, 7, 6, 6, 6, 6, 5, 5, 7, 6, 6, 5, 6, 5, 6, 5, 5, 5, 6, 7, 7, 5,
       7, 5, 7, 7, 6, 7, 6, 6, 5, 6, 6, 5, 6, 5, 4, 5, 7, 6, 6, 6, 6, 7,
       5, 6, 8, 5, 5, 5, 7, 6, 5, 5, 5, 5, 5, 5, 6, 5, 6, 6, 7, 5, 6, 6,
       7, 5, 6, 5, 6, 5, 6, 5, 6, 5, 7, 7, 5, 6, 6, 6, 6, 5, 6, 6, 7, 6,
       5, 5, 6, 5, 6, 4, 7, 7, 8, 5, 5, 6, 6, 7, 5, 6, 8, 7, 4, 6, 5, 6,
       6, 5, 7, 6, 6, 6, 7, 5, 6, 7, 5, 6, 6, 5, 6, 5, 7, 7, 6, 7, 5, 7,
       7, 6, 5, 6, 5, 6, 6, 5, 6, 5, 6, 6, 5, 6, 5, 5, 7, 5, 5, 5, 6, 5,
       5, 6, 6, 5, 5, 7, 6, 5, 6, 5, 5, 6, 5, 5, 5, 5, 5, 5, 7, 5, 5, 5,
       6, 6, 5, 7, 5, 5, 6, 6, 6, 5, 6, 5, 5, 5, 5, 6, 5, 5, 5, 5, 6, 7,
       5, 6, 5, 5, 7, 5, 5, 5, 6, 7, 6, 5, 6, 6, 5,

In [13]:
x_train

array([[ 7.4  ,  1.185,  0.   , ...,  3.63 ,  0.54 , 10.7  ],
       [ 6.9  ,  0.57 ,  0.   , ...,  3.41 ,  0.52 , 10.8  ],
       [ 6.6  ,  0.725,  0.09 , ...,  3.35 ,  0.49 , 10.8  ],
       ...,
       [11.5  ,  0.18 ,  0.51 , ...,  3.28 ,  0.97 , 10.1  ],
       [ 8.3  ,  0.54 ,  0.28 , ...,  3.39 ,  0.61 , 10.   ],
       [ 7.1  ,  0.34 ,  0.28 , ...,  3.45 ,  0.48 ,  9.4  ]])

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
ntrain = y_train.reshape(len(y_train), 1)
ntest = y_test.reshape(len(y_test), 1)

In [16]:
ntrain

array([[3],
       [5],
       [6],
       ...,
       [6],
       [6],
       [5]])

In [17]:
ntest

array([[5],
       [5],
       [5],
       [6],
       [5],
       [7],
       [5],
       [5],
       [5],
       [6],
       [6],
       [5],
       [7],
       [5],
       [6],
       [7],
       [6],
       [5],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [5],
       [5],
       [5],
       [6],
       [5],
       [5],
       [5],
       [5],
       [6],
       [5],
       [5],
       [5],
       [3],
       [6],
       [6],
       [6],
       [6],
       [5],
       [6],
       [5],
       [5],
       [6],
       [6],
       [6],
       [5],
       [5],
       [5],
       [6],
       [5],
       [5],
       [6],
       [6],
       [7],
       [6],
       [5],
       [5],
       [7],
       [7],
       [4],
       [5],
       [6],
       [5],
       [6],
       [5],
       [6],
       [5],
       [5],
       [5],
       [6],
       [7],
       [5],
       [6],
       [6],
       [6],
       [7],
       [6],
       [7],
       [5],
       [4],
    

In [18]:
x_sc = StandardScaler()
y_sc = StandardScaler()

In [19]:
xn_train = x_sc.fit_transform(x_train)
yn_train = y_sc.fit_transform(ntrain)

In [20]:
xn_test = x_sc.transform(x_test)
yn_test = y_sc.transform(ntest)

In [21]:
len(xn_train)

1279

In [22]:
xn_train

array([[-0.53839527,  3.61380433, -1.39192448, ...,  2.09728194,
        -0.68616909,  0.27929036],
       [-0.82741045,  0.21126756, -1.39192448, ...,  0.6573005 ,
        -0.80635674,  0.37426418],
       [-1.00081955,  1.06881748, -0.93044859, ...,  0.26457829,
        -0.98663823,  0.37426418],
       ...,
       [ 1.83152916, -1.94643868,  1.22310553, ..., -0.19359762,
         1.89786552, -0.29055257],
       [-0.01816796,  0.04529016,  0.04377827, ...,  0.5263931 ,
        -0.26551229, -0.38552639],
       [-0.71180438, -1.06122586,  0.04377827, ...,  0.91911531,
        -1.04673206, -0.95536932]])

In [23]:
len(xn_test)

320

In [24]:
xn_test

array([[ 0.32865025, -1.22720326,  1.53075612, ..., -0.32450502,
        -0.74626292, -0.67044786],
       [-0.19157706,  3.58614142, -0.31514742, ...,  0.19912459,
        -1.10682588,  0.08934272],
       [ 0.44425632, -0.06536144,  0.30015376, ..., -0.45541242,
        -0.32560612, -1.05034314],
       ...,
       [-0.19157706, -1.94643868,  0.50525415, ..., -2.74629198,
        -1.28710737,  2.1787668 ],
       [-0.76960741,  0.10061596, -0.7253482 , ...,  0.33003199,
        -0.38569995, -0.67044786],
       [-0.65400134,  0.48789657, -1.08427389, ...,  1.31183752,
        -0.68616909, -0.8603955 ]])

In [25]:
yn_train

array([[-3.235678 ],
       [-0.7664464],
       [ 0.4681694],
       ...,
       [ 0.4681694],
       [ 0.4681694],
       [-0.7664464]])

In [26]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import PolynomialFeatures

In [27]:
r_reg = RandomForestRegressor()
l_reg = LinearRegression()
d_reg = DecisionTreeRegressor()
s_reg = SVR()
p_reg = LinearRegression()

In [28]:
x_pol = PolynomialFeatures(degree=1)
x_pol = x_pol.fit_transform(xn_train)

In [29]:
temp = PolynomialFeatures(degree=1)
temp = temp.fit_transform(xn_test)

In [30]:
r_reg.fit(xn_train, yn_train)
l_reg.fit(xn_train, yn_train)
d_reg.fit(xn_train, yn_train)
s_reg.fit(xn_train, yn_train)
p_reg.fit(x_pol, yn_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [31]:
r_pred = r_reg.predict(xn_test)
l_pred = l_reg.predict(xn_test)
d_pred = d_reg.predict(xn_test)
s_pred = s_reg.predict(xn_test)
p_pred = p_reg.predict(temp)

In [32]:

from sklearn.metrics import r2_score

In [33]:
r = r2_score(yn_test, r_pred)
l = r2_score(yn_test, l_pred)
d = r2_score(yn_test, d_pred)
s = r2_score(yn_test, s_pred)
p = r2_score(yn_test, p_pred)

In [34]:
print(r, l, d, s, p)

0.4941042612887723 0.28423973016576465 0.04264389018926984 0.4168039038991409 0.28423973016576465
